name: Release CI

on:
  push:
    branches:
      - main

permissions:
  contents: write # This is required to create a release

concurrency:
  group: "test-and-dist"
  cancel-in-progress: true

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: ğŸš€ Setup
        uses: ./.github/actions/setup-node-pnpm

      - name: ğŸ§¹ Lint code
        run: pnpm all

      - name: ğŸ§ª Run tests
        run: pnpm test

      - name: ğŸ—ï¸ Build the distribution
        continue-on-error: true
        run: pnpm run build || true

      - name: ğŸ” Check for uncommitted changes
        run: |
          if [[ -n $(git diff --exit-code) ]]; then
            echo "Built files are not up to date"
            echo $(git diff --exit-code)
            exit 1
          fi

  dist:
    runs-on: ubuntu-latest
    needs: test-and-lint
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: ğŸš€ Setup
        uses: ./.github/actions/setup-node-pnpm

      # Setup git config to allow pushes
      - name: Setup git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run release
